[user]
name = "hanna"
email = "hanna@hanna.lol"

[signing]
sign-all = true
backend = "gpg"
key = "F47491837959F4D2"

[ui]
conflict-marker-style = "snapshot"
default-command = ["status"]
diff.format = "git"
editor = "helix"

[templates]
log_node = '''
coalesce(
  if(current_working_copy, "●"),
  if(immutable, "⊗", "○"),
)
'''

[template-aliases]
'format_short_signature(signature)' = 'signature.email().local()'
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_id(id)' = 'id.shortest(7)'

[git]
push-bookmark-prefix = "hanna/"
private-commits = "description(glob:'local:*')"

[snapshot]
max-new-file-size = "5MiB"
