#!/usr/bin/env sh

set -e

GUEST="$1"
STATE="$2"
BASE="$(dirname $0)"

if [ "$STATE" = "prepare" ]; then
  sh "$BASE/$GUEST/prepare.sh"
elif [ "$STATE" = "release" ]; then
  sh "$BASE/$GUEST/release.sh"
fi
