format = "[](#2a2a2a)$directory[](fg:#2a2a2a bg:#4a4a4a)$git_branch[](#4a4a4a) "

scan_timeout = 60
command_timeout = 3600
add_newline = false

[directory]
truncate_to_repo = false
format = "[󰉋 $path ](bg:#2a2a2a fg:#FFFFFF)"

[git_branch]
format = "[ 󰘬 $branch ](bg:#4a4a4a fg:#FFFFFF)"
