#!/bin/zsh

# XDG Standard Directories
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Software Directory Paths
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_history"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
export MISE_CONFIG_DIR="$XDG_CONFIG_HOME/mise"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/golang"

# Path Environment Variable
export PATH="$PATH:$HOME/.local/bin"
hash -d win=/mnt/c/Users/Hanna

# Environment Variables
export PODMAN_IGNORE_CGROUPSV1_WARNING="1"
export COLORTERM="truecolor"
export EDITOR="helix"

# Helix Command Alias
function hx() {
  $(command -v helix) "$@"
  printf '\033[5 q'
}

# Command Aliases
alias paru="paru --color=always"
alias cat="bat"
alias ls="lsd"

# History Configuration
setopt SHARE_HISTORY
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=1000
