#!/bin/zsh

# XDG Standard Directories
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Software Directory Paths
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_history"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
export MISE_CONFIG_DIR="$XDG_CONFIG_HOME/mise"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/golang"

# Path Environment Variable
export PATH="$PATH:$HOME/.local/bin"

# Environment Variables
export COLORTERM="truecolor"
export EDITOR="helix"

# Command Aliases
alias paru="paru --color=always"
alias hx="helix"
alias cat="bat"
alias ls="lsd"

# History Configuration
setopt SHARE_HISTORY
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=1000
