#!/bin/zsh

if [ ! -z "$(command -v ollama)" ] && [ -z "$(pgrep ollama)" ]; then
  # Automatically run the ollama server daemon and create data directory
  [ ! -d "$XDG_DATA_HOME/ollama" ] && mkdir -p "$XDG_DATA_HOME/ollama"
  nohup ollama serve &> $XDG_DATA_HOME/ollama/ollama.log &
fi
